#
# Copyright (c) 2024–2025, Daily
#
# SPDX-License-Identifier: BSD 2-Clause License
#

"""pipecat-quickstart - Pipecat Voice Agent

This bot uses a cascade pipeline: Speech-to-Text → LLM → Text-to-Speech

Generated by Pipecat CLI

Local services:
- Whisper (Speech-to-Text)
- Ollama (LLM)
- Piper (Text-to-Speech)

Run the bot using::

    uv run bot.py
"""

import asyncio
import os
import sys

from dotenv import load_dotenv
from loguru import logger
from pipecat.audio.vad.silero import SileroVADAnalyzer
from pipecat.frames.frames import (
    Frame,
    InterimTranscriptionFrame,
    LLMRunFrame,
    TranscriptionFrame,
)
from pipecat.pipeline.pipeline import Pipeline
from pipecat.pipeline.worker import PipelineParams, PipelineWorker
from pipecat.processors.aggregators.llm_context import LLMContext
from pipecat.processors.aggregators.llm_response_universal import (
    LLMContextAggregatorPair,
    LLMUserAggregatorParams,
)
from pipecat.processors.audio.vad_processor import VADProcessor
from pipecat.processors.frame_processor import FrameDirection, FrameProcessor
from pipecat.runner.types import RunnerArguments
from pipecat.runner.utils import create_transport
from pipecat.services.ollama.llm import OLLamaLLMService
from pipecat.services.piper.tts import PiperTTSService
from pipecat.services.whisper.stt import WhisperSTTService
from pipecat.transports.base_transport import BaseTransport
from pipecat.transports.local.audio import (
    LocalAudioTransport,
    LocalAudioTransportParams,
)
from pipecat.workers.runner import WorkerRunner
from pipecat_whisker import WhiskerServer

load_dotenv(override=True)

logger.remove(0)
logger.add(sys.stderr, level=os.getenv("LOG_LEVEL", "INFO").upper())


# custom frame processor to log transcriptions
class TranscriptionLogger(FrameProcessor):
    async def process_frame(self, frame: Frame, direction: FrameDirection):
        await super().process_frame(frame, direction)

        if isinstance(frame, TranscriptionFrame):
            logger.info(f"Transcription: {frame.text}")
        elif isinstance(frame, InterimTranscriptionFrame):
            logger.info(f"Interim transcription: {frame.text}")

        await self.push_frame(frame, direction)


async def run_bot() -> None:
    """Run the voice bot for this session.

    Args:
        transport: The transport for this session, built by ``create_transport``
            (or by hand for the dial-out/SIP production flows).
        runner_args: Runner session arguments. Carries the request ``body``
            (e.g. dial-out settings, SIP call details) and ``session_id``; the
            standard web/telephony pipelines don't need it.
    """

    logger.info("Starting bot")

    transport = LocalAudioTransport(
        LocalAudioTransportParams(audio_in_enabled=True, input_device_index=0)
    )
    vad_processor = VADProcessor(vad_analyzer=SileroVADAnalyzer())

    # Speech-to-Text service
    stt = WhisperSTTService(
        settings=WhisperSTTService.Settings(
            model=os.getenv("WHISPER_MODEL", "base"),
        ),
        device=os.getenv("WHISPER_DEVICE", "cuda"),
        compute_type=os.getenv("WHISPER_COMPUTE_TYPE", "float16"),
    )

    tl = TranscriptionLogger()

    # LLM service
    # llm = OLLamaLLMService(
    #     model=os.getenv("OLLAMA_MODEL", "llama3"),
    #     host=os.getenv("OLLAMA_HOST", "http://localhost:11434"),
    # )

    # Text-to-Speech service
    # tts = PiperTTSService(
    #     model_name=os.getenv("PIPER_MODEL_NAME", "en_US-amy-medium"),
    #     voice_id=os.getenv("PIPER_VOICE_ID", "amy"),
    # )

    # context = LLMContext()
    # user_aggregator, assistant_aggregator = LLMContextAggregatorPair(
    #     context,
    #     user_params=LLMUserAggregatorParams(vad_analyzer=SileroVADAnalyzer()),
    # )

    # Pipeline - assembled from reusable components
    pipeline = Pipeline(
        [
            transport.input(),
            vad_processor,
            stt,
            tl,
            # user_aggregator,
            # llm,
            # tts,
            transport.output(),
            # assistant_aggregator,
        ]
    )

    worker = PipelineWorker(
        pipeline,
        params=PipelineParams(
            enable_metrics=True,
            enable_usage_metrics=True,
        ),
    )

    @worker.event_handler("on_pipeline_started")
    async def on_pipeline_started(worker, frame):
        logger.info("Pipeline is running and ready!")

    @worker.event_handler("on_pipeline_finished")
    async def on_pipeline_finished(worker, frame):
        logger.info("Pipeline has stopped")

    @worker.event_handler("on_pipeline_error")
    async def on_pipeline_error(worker, frame):
        logger.error(f"Pipeline error occurred: {frame}")

    @worker.event_handler("on_idle_timeout")
    async def on_idle_timeout(worker):
        logger.info("No activity detected — pipeline is idle")

    runner = WorkerRunner(handle_sigint=False)

    whisker = WhiskerServer()
    worker.add_observer(whisker.create_observer(worker))
    await runner.add_workers(whisker, worker)
    await runner.run()


async def bot():
    """Main bot entry point."""
    await run_bot()


if __name__ == "__main__":
    asyncio.run(bot())
