#
# Copyright (c) 2024–2025, Daily
#
# SPDX-License-Identifier: BSD 2-Clause License
#

"""pipecat-quickstart - Pipecat Voice Agent

This bot uses a cascade pipeline: Speech-to-Text → LLM → Text-to-Speech

Generated by Pipecat CLI

Local services:
- Whisper (Speech-to-Text)
- Ollama (LLM)
- Piper (Text-to-Speech)

Run the bot using::

    uv run bot.py
"""

import asyncio
import os
import sys
from pathlib import Path

import yaml
from dotenv import load_dotenv
from loguru import logger
from pipecat.audio.vad.silero import SileroVADAnalyzer
from pipecat.frames.frames import (
    Frame,
    InterimTranscriptionFrame,
    LLMRunFrame,
    TranscriptionFrame,
)
from pipecat.observers.loggers.llm_log_observer import LLMLogObserver
from pipecat.observers.loggers.transcription_log_observer import (
    TranscriptionLogObserver,
)
from pipecat.pipeline.pipeline import Pipeline
from pipecat.pipeline.worker import (
    PipelineParams,
    PipelineWorker,
    ProcessorUnusablePolicy,
)
from pipecat.processors.aggregators.llm_context import LLMContext
from pipecat.processors.aggregators.llm_response_universal import (
    LLMContextAggregatorPair,
    LLMUserAggregatorParams,
)
from pipecat.processors.audio.vad_processor import VADProcessor
from pipecat.processors.frame_processor import FrameDirection, FrameProcessor
from pipecat.runner.types import RunnerArguments
from pipecat.runner.utils import create_transport
from pipecat.services.kokoro.tts import KokoroTTSService
from pipecat.services.ollama.llm import OLLamaLLMService
from pipecat.services.piper.tts import PiperTTSService
from pipecat.services.whisper.stt import WhisperSTTService
from pipecat.transports.base_transport import BaseTransport
from pipecat.transports.local.audio import (
    LocalAudioTransport,
    LocalAudioTransportParams,
)
from pipecat.workers.runner import WorkerRunner
from pipecat_whisker import WhiskerServer

load_dotenv(override=True)

CONFIG_PATH = Path(__file__).with_name("config.yaml")
with CONFIG_PATH.open() as config_file:
    CONFIG = yaml.safe_load(config_file)

logger.remove(0)
logger.add(sys.stderr, level=os.getenv("LOG_LEVEL", CONFIG["logging"]["level"]).upper())


async def run_bot() -> None:
    """Run the voice bot for this session.

    Args:
        transport: The transport for this session, built by ``create_transport``
            (or by hand for the dial-out/SIP production flows).
        runner_args: Runner session arguments. Carries the request ``body``
            (e.g. dial-out settings, SIP call details) and ``session_id``; the
            standard web/telephony pipelines don't need it.
    """

    logger.info("Starting bot")

    transport = LocalAudioTransport(
        LocalAudioTransportParams(
            audio_in_enabled=True,
            audio_out_enabled=True,
            input_device_index=CONFIG["audio"]["input_device_index"],
            output_device_index=CONFIG["audio"]["output_device_index"],
        )
    )
    vad_processor = VADProcessor(vad_analyzer=SileroVADAnalyzer())

    # Speech-to-Text service
    stt = WhisperSTTService(
        settings=WhisperSTTService.Settings(
            model=CONFIG["whisper"]["model"],
            language=CONFIG["whisper"]["language"],
        ),
        device=CONFIG["whisper"]["device"],
        compute_type=CONFIG["whisper"]["compute_type"],
    )

    # LLM service
    llm = OLLamaLLMService(
        base_url=CONFIG["ollama"]["host"],
        settings=OLLamaLLMService.Settings(
            model=CONFIG["ollama"]["model"],
            system_instruction=CONFIG["ollama"]["system_instruction"],
            temperature=CONFIG["ollama"]["temperature"],
        ),
    )

    # Text-to-Speech service
    # tts = PiperTTSService(
    #     model_name=CONFIG["piper"]["model_name"],
    #     voice_id=CONFIG["piper"]["voice_id"],
    # )

    tts = KokoroTTSService(
        speed=CONFIG["kokoro"]["speed"],
        settings=KokoroTTSService.Settings(
            voice=CONFIG["kokoro"]["voice"],
            language=CONFIG["kokoro"]["language"],
        ),
    )

    context = LLMContext()
    user_aggregator, assistant_aggregator = LLMContextAggregatorPair(
        context,
        user_params=LLMUserAggregatorParams(vad_analyzer=SileroVADAnalyzer()),
    )

    # Pipeline - assembled from reusable components
    pipeline = Pipeline(
        [
            transport.input(),
            vad_processor,
            stt,
            user_aggregator,
            llm,
            tts,
            transport.output(),
            assistant_aggregator,
        ]
    )

    worker = PipelineWorker(
        pipeline,
        params=PipelineParams(
            # enable_metrics=True,
            # enable_usage_metrics=True,
        ),
        observers=[
            TranscriptionLogObserver(),
            LLMLogObserver(),
        ],
        processor_unusable_policy=ProcessorUnusablePolicy.END,
    )

    @worker.event_handler("on_pipeline_started")
    async def on_pipeline_started(worker, frame):
        logger.info("Pipeline is running and ready!")

    @worker.event_handler("on_pipeline_finished")
    async def on_pipeline_finished(worker, frame):
        logger.info("Pipeline has stopped")

    @worker.event_handler("on_pipeline_error")
    async def on_pipeline_error(worker, frame):
        logger.error(f"Pipeline error occurred: {frame}")

    @worker.event_handler("on_idle_timeout")
    async def on_idle_timeout(worker):
        logger.info("No activity detected — pipeline is idle")

    runner = WorkerRunner(handle_sigint=False)

    # whisker = WhiskerServer()
    # worker.add_observer(whisker.create_observer(worker))
    # await runner.add_workers(whisker, worker)
    await runner.add_workers(worker)
    await runner.run()


async def bot():
    """Main bot entry point."""
    await run_bot()


if __name__ == "__main__":
    asyncio.run(bot())
